In [1]:
import pandas as pd
from src.common.utils import get_root_directory
from src.preprocessing.data_loader import DataLoader

In [2]:
root_dir = get_root_directory()
DL = DataLoader(root_dir=root_dir)

In [3]:
DL.load_data()

In [4]:
DL.merge_selected_data(selected_data=['BTC','LTC','sentiment_analysis'])
DL.final_data.columns

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Index(['ETH_D_AvgPrc', 'ETH_D_PrcDir', 'ETH_YF_Op', 'ETH_YF_Hi', 'ETH_YF_Lo',
       'ETH_YF_Cls', 'ETH_YF_Vol', 'ETH_ES_AvgTransFee', 'ETH_ES_AvgGasPrc',
       'ETH_ES_BlkCnt', 'ETH_ES_BlkSz', 'ETH_ES_BlkTm', 'ETH_ES_ActAdd',
       'ETH_ES_DepCon', 'ETH_ES_GasLmt', 'ETH_ES_GasUsd', 'ETH_ES_VerCon',
       'ETH_OL_MktCap', 'ETH_OL_NewAdd', 'ETH_OL_ChnTrans', 'ETH_OL_ChnVol',
       'BTC_D_AvgPrc', 'BTC_YF_Op', 'BTC_YF_Hi', 'BTC_YF_Lo', 'BTC_YF_Cls',
       'BTC_YF_Vol', 'BTC_OL_MktCap', 'BTC_OL_BlkSz', 'BTC_OL_AvgComPwr',
       'BTC_OL_AvgTransFee', 'BTC_OL_MinDif', 'BTC_OL_ActAdd', 'BTC_OL_NewAdd',
       'BTC_OL_ChnTrans', 'BTC_OL_ChnVol', 'BTC_BIC_HshRt', 'LTC_D_AvgPrc',
       'LTC_YF_Op', 'LTC_YF_Hi', 'LTC_YF_Lo', 'LTC_YF_Cls', 'LTC_YF_Vol',
       'LTC_OL_MktCap', 'LTC_OL_BlkSz', 'LTC_OL_AvgComPwr',
       'LTC_OL_AvgTransFee', 'LTC_OL_MinDif', 'LTC_OL_ActAdd', 'LTC_OL_NewAdd',
       'LTC_OL_ChnTrans', 'LTC_BIC_HshRt', 'D_VADER_AvgScr_In',
       'D_VADER_Sent_AvgIn', 'D_VADER_AvgScr_Ex', 'D_VADER_Sent_AvgEx',
       'D_FINBERT_AvgScr_In', 'D_FINBERT_Sent_AvgIn', 'D_FINBERT_AvgScr_Ex',
       'D_FINBERT_Sent_AvgEx', 'D_CRYPTOBERT_AvgScr_In',
       'D_CRYPTOBERT_Sent_AvgIn', 'D_CRYPTOBERT_AvgScr_Ex',
       'D_CRYPTOBERT_Sent_AvgEx'],
      dtype='object')

In [4]:
DL.final_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2335 entries, 2017-11-10 to 2024-04-01
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ETH_D_AvgPrc        2335 non-null   float64
 1   ETH_D_PrcDir        2335 non-null   float64
 2   ETH_YF_Op           2335 non-null   float64
 3   ETH_YF_Hi           2335 non-null   float64
 4   ETH_YF_Lo           2335 non-null   float64
 5   ETH_YF_Cls          2335 non-null   float64
 6   ETH_YF_Vol          2335 non-null   int64
 7   ETH_ES_AvgTransFee  2335 non-null   float64
 8   ETH_ES_AvgGasPrc    2335 non-null   int64
 9   ETH_ES_BlkCnt       2335 non-null   int64
 10  ETH_ES_BlkSz        2335 non-null   int64
 11  ETH_ES_BlkTm        2335 non-null   float64
 12  ETH_ES_ActAdd       2335 non-null   int64
 13  ETH_ES_DepCon       2335 non-null   int64
 14  ETH_ES_GasLmt       2335 non-null   int64
 15  ETH_ES_GasUsd       2335 non-null   int64
 16  ETH_ES_VerCon       2335 non-null   int64
 17  ETH_OL_MktCap       2335 non-null   float64
 18  ETH_OL_NewAdd       2335 non-null   float64
 19  ETH_OL_ChnTrans     2335 non-null   int64
 20  ETH_OL_ChnVol       2335 non-null   float64
dtypes: float64(11), int64(10)
memory usage: 401.3 KB

In [5]:
DL.merge_selected_data(selected_data=["BTC","LTC","sentiment_analysis"])

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

In [6]:
DL.set_time_range(start_date=None, end_date=None)

start_date is before the earliest date in the dataset, setting to the earliest date.
end_date is after the latest date in the dataset, setting to the latest date.

In [7]:
DL.final_data.columns

Index(['ETH_D_AvgPrc', 'ETH_D_PrcDir', 'ETH_YF_Op', 'ETH_YF_Hi', 'ETH_YF_Lo',
       'ETH_YF_Cls', 'ETH_YF_Vol', 'ETH_ES_AvgTransFee', 'ETH_ES_AvgGasPrc',
       'ETH_ES_BlkCnt', 'ETH_ES_BlkSz', 'ETH_ES_BlkTm', 'ETH_ES_ActAdd',
       'ETH_ES_DepCon', 'ETH_ES_GasLmt', 'ETH_ES_GasUsd', 'ETH_ES_VerCon',
       'ETH_OL_MktCap', 'ETH_OL_NewAdd', 'ETH_OL_ChnTrans', 'ETH_OL_ChnVol',
       'BTC_D_AvgPrc', 'BTC_YF_Op', 'BTC_YF_Hi', 'BTC_YF_Lo', 'BTC_YF_Cls',
       'BTC_YF_Vol', 'BTC_OL_MktCap', 'BTC_OL_BlkSz', 'BTC_OL_AvgComPwr',
       'BTC_OL_AvgTransFee', 'BTC_OL_MinDif', 'BTC_OL_ActAdd', 'BTC_OL_NewAdd',
       'BTC_OL_ChnTrans', 'BTC_OL_ChnVol', 'BTC_BIC_HshRt', 'LTC_D_AvgPrc',
       'LTC_YF_Op', 'LTC_YF_Hi', 'LTC_YF_Lo', 'LTC_YF_Cls', 'LTC_YF_Vol',
       'LTC_OL_MktCap', 'LTC_OL_BlkSz', 'LTC_OL_AvgComPwr',
       'LTC_OL_AvgTransFee', 'LTC_OL_MinDif', 'LTC_OL_ActAdd', 'LTC_OL_NewAdd',
       'LTC_OL_ChnTrans', 'LTC_BIC_HshRt', 'D_VADER_AvgScr_In',
       'D_VADER_Sent_AvgIn', 'D_VADER_AvgScr_Ex', 'D_VADER_Sent_AvgEx',
       'D_FINBERT_AvgScr_In', 'D_FINBERT_Sent_AvgIn', 'D_FINBERT_AvgScr_Ex',
       'D_FINBERT_Sent_AvgEx', 'D_CRYPTOBERT_AvgScr_In',
       'D_CRYPTOBERT_Sent_AvgIn', 'D_CRYPTOBERT_AvgScr_Ex',
       'D_CRYPTOBERT_Sent_AvgEx'],
      dtype='object')

In [8]:
DL.final_data

,ETH_D_AvgPrc,ETH_D_PrcDir,ETH_YF_Op,ETH_YF_Hi,ETH_YF_Lo,ETH_YF_Cls,ETH_YF_Vol,ETH_ES_AvgTransFee,ETH_ES_AvgGasPrc,ETH_ES_BlkCnt,...,D_VADER_AvgScr_Ex,D_VADER_Sent_AvgEx,D_FINBERT_AvgScr_In,D_FINBERT_Sent_AvgIn,D_FINBERT_AvgScr_Ex,D_FINBERT_Sent_AvgEx,D_CRYPTOBERT_AvgScr_In,D_CRYPTOBERT_Sent_AvgIn,D_CRYPTOBERT_AvgScr_Ex,D_CRYPTOBERT_Sent_AvgEx
Date,,,,,,,,,,,,,,,,,,,,,
2017-11-10,309.795990,-1.0,320.670990,324.717987,294.541992,299.252991,8.859860e+08,0.19,1.503609e+10,6300.0,...,0.267875,1,-0.061600,-1,-0.149600,-1,0.126681,1,0.538396,1
2017-11-11,307.727997,-1.0,298.585999,319.453003,298.191986,314.681000,8.423010e+08,0.19,1.539475e+10,6267.0,...,0.112014,1,-0.144046,-1,-0.864277,-1,0.105284,1,0.631707,1
2017-11-12,310.066002,1.0,314.690002,319.153015,298.513000,307.907990,1.613480e+09,0.21,1.801127e+10,6245.0,...,0.088433,1,0.117165,1,0.439368,1,0.251211,1,0.538310,1
2017-11-13,314.795250,1.0,307.024994,328.415009,307.024994,316.716003,1.041890e+09,0.22,1.660364e+10,6225.0,...,0.078931,1,-0.050870,-1,-0.197827,-1,0.146051,1,0.464707,1
2017-11-14,327.833504,1.0,316.763000,340.177002,316.763000,337.631012,1.069680e+09,0.24,1.670441e+10,6122.0,...,0.296356,1,0.048023,0,0.312147,1,0.123785,1,0.643684,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-28,3534.136902,-1.0,3500.216064,3609.705322,3465.332275,3561.293945,1.641967e+10,11.27,3.788605e+10,7028.0,...,0.037374,0,0.058417,1,0.234912,1,0.082416,1,0.472018,1
2024-03-29,3533.061218,-1.0,3561.011719,3583.701416,3475.725586,3511.806152,1.271270e+10,8.62,2.908396e+10,7122.0,...,0.118291,1,0.087957,1,0.330719,1,0.104424,1,0.490794,1
2024-03-30,3518.939636,-1.0,3511.827637,3566.084473,3489.902100,3507.944336,9.389067e+09,7.67,2.502699e+10,7109.0,...,0.187781,1,0.184344,1,0.670342,1,0.072131,1,0.412178,1
2024-03-31,3579.567444,1.0,3507.951660,3655.218994,3507.242676,3647.856445,1.049988e+10,7.58,2.375656e+10,7106.0,...,0.075188,1,0.030599,0,0.091797,1,0.132684,1,0.597076,1
2024-04-01,3554.918518,-1.0,3647.819580,3648.129150,3418.695312,3505.030029,1.600210e+10,8.74,2.846122e+10,7120.0,...,0.132067,1,0.031695,0,0.124861,1,0.088046,1,0.520269,1

In [9]:
DL.lag_features(exclude_cols=["ETH_D_AvgPrc"], lag=1)

In [10]:
DL.final_data

,ETH_D_AvgPrc,ETH_D_PrcDir,ETH_YF_Op,ETH_YF_Hi,ETH_YF_Lo,ETH_YF_Cls,ETH_YF_Vol,ETH_ES_AvgTransFee,ETH_ES_AvgGasPrc,ETH_ES_BlkCnt,...,D_VADER_AvgScr_Ex,D_VADER_Sent_AvgEx,D_FINBERT_AvgScr_In,D_FINBERT_Sent_AvgIn,D_FINBERT_AvgScr_Ex,D_FINBERT_Sent_AvgEx,D_CRYPTOBERT_AvgScr_In,D_CRYPTOBERT_Sent_AvgIn,D_CRYPTOBERT_AvgScr_Ex,D_CRYPTOBERT_Sent_AvgEx
Date,,,,,,,,,,,,,,,,,,,,,
2017-11-11,307.727997,-1.0,320.670990,324.717987,294.541992,299.252991,8.859860e+08,0.19,1.503609e+10,6300.0,...,0.267875,1.0,-0.061600,-1.0,-0.149600,-1.0,0.126681,1.0,0.538396,1.0
2017-11-12,310.066002,-1.0,298.585999,319.453003,298.191986,314.681000,8.423010e+08,0.19,1.539475e+10,6267.0,...,0.112014,1.0,-0.144046,-1.0,-0.864277,-1.0,0.105284,1.0,0.631707,1.0
2017-11-13,314.795250,1.0,314.690002,319.153015,298.513000,307.907990,1.613480e+09,0.21,1.801127e+10,6245.0,...,0.088433,1.0,0.117165,1.0,0.439368,1.0,0.251211,1.0,0.538310,1.0
2017-11-14,327.833504,1.0,307.024994,328.415009,307.024994,316.716003,1.041890e+09,0.22,1.660364e+10,6225.0,...,0.078931,1.0,-0.050870,-1.0,-0.197827,-1.0,0.146051,1.0,0.464707,1.0
2017-11-15,335.511490,1.0,316.763000,340.177002,316.763000,337.631012,1.069680e+09,0.24,1.670441e+10,6122.0,...,0.296356,1.0,0.048023,0.0,0.312147,1.0,0.123785,1.0,0.643684,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-28,3534.136902,-1.0,3587.313721,3664.383057,3460.393555,3500.115234,1.875308e+10,11.41,3.981720e+10,6921.0,...,0.202080,1.0,0.079012,1.0,0.336437,1.0,0.118715,1.0,0.580385,1.0
2024-03-29,3533.061218,-1.0,3500.216064,3609.705322,3465.332275,3561.293945,1.641967e+10,11.27,3.788605e+10,7028.0,...,0.037374,0.0,0.058417,1.0,0.234912,1.0,0.082416,1.0,0.472018,1.0
2024-03-30,3518.939636,-1.0,3561.011719,3583.701416,3475.725586,3511.806152,1.271270e+10,8.62,2.908396e+10,7122.0,...,0.118291,1.0,0.087957,1.0,0.330719,1.0,0.104424,1.0,0.490794,1.0
2024-03-31,3579.567444,-1.0,3511.827637,3566.084473,3489.902100,3507.944336,9.389067e+09,7.67,2.502699e+10,7109.0,...,0.187781,1.0,0.184344,1.0,0.670342,1.0,0.072131,1.0,0.412178,1.0
2024-04-01,3554.918518,1.0,3507.951660,3655.218994,3507.242676,3647.856445,1.049988e+10,7.58,2.375656e+10,7106.0,...,0.075188,1.0,0.030599,0.0,0.091797,1.0,0.132684,1.0,0.597076,1.0

In [11]:
DL.select_features(features=["ETH_D_AvgPrc"])

In [12]:
DL.final_data

            ETH_D_AvgPrc
Date
2017-11-11    307.727997
2017-11-12    310.066002
2017-11-13    314.795250
2017-11-14    327.833504
2017-11-15    335.511490
...                  ...
2024-03-28   3534.136902
2024-03-29   3533.061218
2024-03-30   3518.939636
2024-03-31   3579.567444
2024-04-01   3554.918518

[2334 rows x 1 columns]

In [13]:
train, test = DL.data_split(split_type="test_train", split_size=0.2)

In [14]:
train, val = DL.data_split(split_type="train_val", split_size=0.2)

In [15]:
train.index.min()

Timestamp('2017-11-11 00:00:00')

In [16]:
train.index.max()

Timestamp('2021-12-14 00:00:00')

In [18]:
val.index.min()

Timestamp('2021-12-15 00:00:00')

In [19]:
val.index.max()

Timestamp('2022-12-22 00:00:00')

In [20]:
test.index.max()

Timestamp('2024-04-01 00:00:00')

In [21]:
test.index.min()

Timestamp('2022-12-23 00:00:00')