In [1]:
import pandas as pd
from src.common.utils import get_root_directory

In [2]:
root_dir = get_root_directory()
sentiment_data = pd.read_csv(f"{root_dir}/data/final/sentiment_analysis.csv", index_col="Date", parse_dates=True)

In [3]:
sentiment_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 156574 entries, 2017-11-09 to 2024-08-11
Data columns (total 8 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   News Headline          156574 non-null  object
 1   Publisher              156574 non-null  object
 2   D_VADER_Score          156574 non-null  float64
 3   D_VADER_Sent           156574 non-null  int64
 4   D_FINBERT_ConScore     156574 non-null  float64
 5   D_FINBERT_Sent         156574 non-null  int64
 6   D_CRYPTOBERT_ConScore  156574 non-null  float64
 7   D_CRYPTOBERT_Sent      156574 non-null  int64
dtypes: float64(3), int64(3), object(2)
memory usage: 10.8+ MB

In [4]:
from src.preprocessing.feature_generator import FeatureGenerator

In [5]:
FG = FeatureGenerator(input_data=sentiment_data, data_tag="sentiment")

In [6]:
final_data = FG.generate_features()

             Date                                      News Headline  \
0      2017-11-09  Hong Kong Fintech Innovation Lab Led with Bloc...
2      2017-11-09  Ethereum cryptocurrency value dropped due to w...
9      2017-11-09  There were more than 26,000 new blockchain pro...
10     2017-11-09  'Irrational exuberance' in ICOs but the tech i...
11     2017-11-09  Transparent Transactions: How Blockchain Payme...
...           ...                                                ...
156567 2024-08-11  Avalanche Price Prediction 2024-30: A Good Inv...
156569 2024-08-11  Monero Price Prediction 2024-2030: A Good Inve...
156570 2024-08-11  Could Bitcoin Crash? Celsius Slaps Tether with...
156572 2024-08-11  Best Top 5 Crypto to Buy (Short List) / X100 M...
156573 2024-08-11  GrabPay warns users not to buy cryptocurrency ...

                  Publisher  D_VADER_Score  D_VADER_Sent  D_FINBERT_ConScore  \
0                    Forbes         0.3818             1            0.590740
2              Inquirer.net         0.4404             1            0.967870
9                      CNBC         0.4019             1            0.938380
10                     CNBC        -0.1779            -1            0.845581
11                   Forbes         0.4215             1            0.860937
...                     ...            ...           ...                 ...
156567        Cryptopolitan         0.4404             1            0.816851
156569        Cryptopolitan         0.4404             1            0.828010
156570           Cryptonews        -0.5574            -1            0.854273
156572    Crypto News Flash         0.7184             1            0.914183
156573  Yahoo News Malaysia         0.0772             1            0.758402

        D_FINBERT_Sent  D_CRYPTOBERT_ConScore  D_CRYPTOBERT_Sent
0                    0               0.518976                  0
2                   -1               0.948679                  0
9                    0               0.866684                  0
10                   0               0.973080                  0
11                   0               0.744360                  0
...                ...                    ...                ...
156567               0               0.466416                  0
156569               0               0.580684                  0
156570              -1               0.537498                  0
156572               0               0.745514                  0
156573               0               0.954350                  0

[79398 rows x 9 columns]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

             Date                                      News Headline  \
2      2017-11-09  Ethereum cryptocurrency value dropped due to w...
8      2017-11-09  Code bug freezes $150m of Ethereum crypto-cash...
15     2017-11-09  Cracks Appear as Critics Label Bitconnect a Po...
16     2017-11-09  Bitcoin peaks again on Lux-based Bitstamp - De...
23     2017-11-09  Bitcoin price LIVE: Bitcoin surges 11 per cent...
...           ...                                                ...
156553 2024-08-11  Ethereum Open Interest Drops 40% In August – W...
156559 2024-08-11  Costa Rica Heist: Israeli Tourists Lose $700,0...
156560 2024-08-11  XRP Surges 17% Following Legal Victory Over SE...
156561 2024-08-11  Bitcoin Falls Below $53K Mark As Global Financ...
156570 2024-08-11  Could Bitcoin Crash? Celsius Slaps Tether with...

                     Publisher  D_VADER_Score  D_VADER_Sent  \
2                 Inquirer.net         0.4404             1
8                      BBC.com        -0.0258             0
15            Bitcoin.com News        -0.2960            -1
16                   Delano.lu         0.0000             0
23                     Express         0.0000             0
...                        ...            ...           ...
156553                 NewsBTC         0.4588             1
156559              Bitcoinist        -0.0258             0
156560  The Currency Analytics         0.1280             1
156561                     MSN        -0.3818            -1
156570              Cryptonews        -0.5574            -1

        D_FINBERT_ConScore  D_FINBERT_Sent  D_CRYPTOBERT_ConScore  \
2                 0.967870              -1               0.948679
8                 0.750443              -1               0.935448
15                0.962750              -1               0.915315
16                0.837416               1               0.536171
23                0.852476               1               0.740224
...                    ...             ...                    ...
156553            0.878411              -1               0.838831
156559            0.898894              -1               0.501922
156560            0.840059               1               0.563675
156561            0.947117              -1               0.630036
156570            0.854273              -1               0.537498

        D_CRYPTOBERT_Sent
2                       0
8                       0
15                     -1
16                      1
23                      0
...                   ...
156553                  0
156559                  0
156560                  1
156561                  0
156570                  0

[37711 rows x 9 columns]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

             Date                                      News Headline  \
3      2017-11-09  Ambrosus: Digitalising the Global Trade with B...
6      2017-11-09  Cryptography for Global Health - Harvard Medic...
13     2017-11-09                      Samantha Chang - Investopedia
14     2017-11-09  Here's What's Next for Bitcoin Now That the 2x...
15     2017-11-09  Cracks Appear as Critics Label Bitconnect a Po...
...           ...                                                ...
156546 2024-08-11  Queens Bitcoin Heist: Seven Charged With Grand...
156547 2024-08-11  This Ethereum Chart Could Signal a MASSIVE Tre...
156557 2024-08-11  Russia Legalize Crypto Mining in Strategic Eco...
156560 2024-08-11  XRP Surges 17% Following Legal Victory Over SE...
156564 2024-08-11  BlockDAG Dominates as Bitcoin, ICP Struggle - ...

                     Publisher  D_VADER_Score  D_VADER_Sent  \
3       Open Access Government         0.0000             0
6       Harvard Medical School         0.0000             0
13                Investopedia         0.0000             0
14                      Forbes         0.0000             0
15            Bitcoin.com News        -0.2960            -1
...                        ...            ...           ...
156546        Bitcoin.com News         0.2960             1
156547                     MSN         0.0000             0
156557         AlexaBlockchain         0.0000             0
156560  The Currency Analytics         0.1280             1
156564         Crypto Reporter        -0.2732            -1

        D_FINBERT_ConScore  D_FINBERT_Sent  D_CRYPTOBERT_ConScore  \
3                 0.852426               0               0.549529
6                 0.924794               0               0.606309
13                0.940413               0               0.587454
14                0.934834               0               0.352829
15                0.962750              -1               0.915315
...                    ...             ...                    ...
156546            0.528596              -1               0.519616
156547            0.885793               0               0.497666
156557            0.883702               0               0.514959
156560            0.840059               1               0.563675
156564            0.775002               0               0.584005

        D_CRYPTOBERT_Sent  D_FINBERT_AvgScr_In
3                       1             0.000000
6                       1             0.000000
13                      1             0.000000
14                     -1             0.000000
15                     -1            -0.962750
...                   ...                  ...
156546                  1            -0.528596
156547                  1             0.000000
156557                  1             0.000000
156560                  1             0.840059
156564                  1             0.000000

[33076 rows x 10 columns]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/2468 [00:00<?, ?it/s]

In [8]:
final_data["2017-11-09":"2024-04-01"].info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2336 entries, 2017-11-09 to 2024-04-01
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   D_VADER_AvgScr_In        2336 non-null   float64
 1   D_VADER_Sent_AvgIn       2336 non-null   int64
 2   D_VADER_AvgScr_Ex        2336 non-null   float64
 3   D_VADER_Sent_AvgEx       2336 non-null   int64
 4   D_FINBERT_AvgScr_In      2336 non-null   float64
 5   D_FINBERT_Sent_AvgIn     2336 non-null   int64
 6   D_FINBERT_AvgScr_Ex      2316 non-null   float64
 7   D_FINBERT_Sent_AvgEx     2336 non-null   int64
 8   D_CRYPTOBERT_AvgScr_In   2336 non-null   float64
 9   D_CRYPTOBERT_Sent_AvgIn  2336 non-null   int64
 10  D_CRYPTOBERT_AvgScr_Ex   2331 non-null   float64
 11  D_CRYPTOBERT_Sent_AvgEx  2336 non-null   int64
dtypes: float64(6), int64(6)
memory usage: 237.2 KB

In [7]:
dropped_neutrals = sentiment_data.drop(sentiment_data[sentiment_data["D_VADER_Sent"] == 0].index)

In [25]:
dropped_neutrals = sentiment_data.drop(sentiment_data[sentiment_data["D_VADER_Sent"] == 0].index)

In [9]:
index = sentiment_data[sentiment_data["D_VADER_Sent"] == 0].index

In [16]:
dropped_neutrals = sentiment_data

In [17]:
dropped_neutrals.drop(index=dropped_neutrals[dropped_neutrals["D_VADER_Sent"] == 0].index)

Empty DataFrame
Columns: [News Headline, Publisher, D_VADER_Score, D_VADER_Sent, D_FINBERT_ConScore, D_FINBERT_Sent, D_CRYPTOBERT_ConScore, D_CRYPTOBERT_Sent]
Index: []

In [9]:
final_data

,D_VADER_AvgScr_In,D_VADER_Sent_AvgIn,D_VADER_AvgScr_Ex,D_VADER_Sent_AvgEx,D_FINBERT_AvgScr_In,D_FINBERT_Sent_AvgIn,D_FINBERT_AvgScr_Ex,D_FINBERT_Sent_AvgEx,D_CRYPTOBERT_AvgScr_In,D_CRYPTOBERT_Sent_AvgIn,D_CRYPTOBERT_AvgScr_Ex,D_CRYPTOBERT_Sent_AvgEx
Date,,,,,,,,,,,,
2017-11-09,0.082633,1,0.202827,1,-0.061348,-1,-0.276067,-1,0.144897,1,0.300940,1
2017-11-10,0.189088,1,0.267875,1,-0.061600,-1,-0.149600,-1,0.126681,1,0.538396,1
2017-11-11,0.065342,1,0.112014,1,-0.144046,-1,-0.864277,-1,0.105284,1,0.631707,1
2017-11-12,0.037093,0,0.088433,1,0.117165,1,0.439368,1,0.251211,1,0.538310,1
2017-11-13,0.036083,0,0.078931,1,-0.050870,-1,-0.197827,-1,0.146051,1,0.464707,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-07,0.051544,1,0.105041,1,0.036685,0,0.102213,1,0.087570,1,0.443930,1
2024-08-08,0.042091,0,0.080019,1,0.075052,1,0.203790,1,0.085785,1,0.431246,1
2024-08-09,0.039904,0,0.087151,1,0.076731,1,0.237117,1,0.116970,1,0.490560,1
2024-08-10,0.057555,1,0.102567,1,0.050577,1,0.128317,1,0.119828,1,0.497469,1
2024-08-11,0.100751,1,0.180269,1,-0.038411,0,-0.156386,-1,0.066093,1,0.418589,1